### ISSUE TITLE
CSS积累

### ISSUE THREAD

**Issue by i-am-annewang** [i-am-annewang/wanghuiying.github.io#15]
1.  不同浏览器内核
```css
/* Chrome, Opera, Safari */
::webkit-input-placeholder {
   color: #ff6600; /*orange*/
}
/* Firefox 19+*/
::-moz-placeholder {
  color: #ff6600;
  opacity: 1; /*提高透明度*/
}

/* Firefox 18 and below*/
:-moz-placeholder {
  color: #ff6600;
   opacity: 1;
}
/* MS IE 10+ */
:-ms-input-placeholder {
   color: #ff6600;
   opacity: 1;
}
```
2. 屏幕自适应
```css
@media screen and (max-width: ${BREAKPOINT - 1}px) {
    padding: ${MOBILE_PADDING}px;
  }
```
